bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_basket, name='add_to_basket'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

just_one_more/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.products,
         name='products'),
    path('<int:product_id>/',
         views.product_detail, name='product_detail'),
    path('add/',
         views.add_product, name='add_product'),
    path('edit/<int:product_id>/',
         views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/',
         views.delete_product, name='delete_product'),
    path('review/<product_id>/',
         views.product_review, name='product_review'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile

# Create your models here.


class Order(models.Model):
    """
    This class will be migrated into the admin, this will generate
    an order report which will be viewable to the user once they
    have created a user account
    """
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=48, null=False, blank=False)
    email = models.EmailField(max_length=256, null=False, blank=False)
    mob_number = models.CharField(max_length=15, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=15, null=True, blank=True)
    city = models.CharField(max_length=30, null=False, blank=False)
    first_address_line = models.CharField(
        max_length=80, null=False, blank=False)
    second_address_line = models.CharField(
        max_length=80, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery = models.DecimalField(
        max_digits=5, decimal_places=2, null=False, default=5)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=256, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generates a random and unique order number
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        updates order total viewable in grand_total
        """

        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))[
            'lineitem_total__sum'] or 0
        self.grand_total = self.order_total + self.delivery
        self.save()

    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=3, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False,
        editable=False)

    def save(self, *args, **kwargs):
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """
    class category models view for the admin
    """
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=256)
    friendly_name = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    """
    class product models view for the admin
    """
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=256, null=True, blank=True)
    name = models.CharField(max_length=256)
    age_rating = models.CharField(max_length=10, null=True, blank=True)
    platform = models.CharField(max_length=256, null=True, blank=True)
    genre = models.CharField(max_length=256, null=True, blank=True)
    sizes = models.BooleanField(default=False, null=True, blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


ONE_TO_FIVE = [
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
]


class Review(models.Model):
    """
    class reviews models view for the admin
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='reviews',
                                on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    user_review = models.TextField(max_length=500, blank=True)
    rate = models.PositiveSmallIntegerField(choices=ONE_TO_FIVE)

    def __str__(self):
        return self.user.username

products/forms.py
from django import forms
from .models import Product, Category, Review


class ProductForm(forms.ModelForm):
    """
    Form creation for adding product
    """
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "border-black rounded-0"


class ReviewForm(forms.ModelForm):
    """
    Form creation for user reviews
    """
    class Meta:
        model = Review
        exclude = ('product', 'user')

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category, Review
from .forms import ProductForm, ReviewForm

# Create your views here.


def products(request):
    """
    This view will show all the products as well as search
    queries and sorting results
    """

    query = None
    sort = None
    categories = None
    direction = None

    products = Product.objects.all()

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sort == 'category':
                sortkey = 'category__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "What you want doesn't exist! Try Again!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """
    This view will show individual product pages depending on which
    product was clicked on. This will display much more detail the
    product view
    """

    product = get_object_or_404(Product, pk=product_id)
    form = ReviewForm()

    context = {
        'product': product,
        'form': form,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """
    Add a product to the shop
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry you need to be a super user to do that')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Product Added')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed, Make sure everything is valid and try again')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product in the shop
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry you need to be a super user to do that')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product Updated')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed, Make sure everything is valid and try again')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the shop """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry you need to be a super user to do that')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


def product_review(request, product_id):
    """
    This is for user reviews on specific products
    """
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.product = product
            review.save()
            messages.success(request, 'User Review Successful')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Review form failed')
    else:
        form = ReviewForm()

    context = {
        'form': form
    }

    return render(request, context)

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}

<div class="header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>

{% endblock %}

{% block content %}

<div class="overlay"></div>
<div class="container p-2">
    <div class="row">
        <div class="col-12">
            <h2 class="fjalla-font mt-4 text-danger">
                Product Management
                <hr>
            </h2>
            <h5 class="bold-font shadows-font">Add a new Product</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form action="{% url 'add_product' %}" method=POST enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <div>
                    <button class="border-0 btn btn-danger btn-lg" type="submit">
                        Add Product
                    </button>
                    <a href="{% url 'products' %}" class="btn btn-dark btn-lg">Back to Products</a>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

{% block postloadjs %}
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}

<div class="header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>

{% endblock %}

{% block content %}

<div class="overlay"></div>
<div class="container p-2">
    <div class="row">
        <div class="col-12">
            <h2 class="fjalla-font mt-4 text-danger">
                Product Management
                <hr>
            </h2>
            <h5 class="bold-font shadows-font">Edit a Product</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form action="{% url 'edit_product' product.id %}" method=POST enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <div>
                    <button class="border-0 btn btn-danger btn-lg" type="submit">
                        Update Product
                    </button>
                    <a href="{% url 'products' %}" class="btn btn-dark btn-lg">Back to Products</a>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

{% block postloadjs %}
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-xl-5 col-sm-10 mt-3">
            {% if product.image %}
            <a href="" class="mx-auto" target="_blank">
                <img src="{{ product.image.url }}"  class="card-image-detail card-img-top"
                    alt="{{ product.name }}">
            </a>
            {% else %}
            <a href="" class="mx-auto">
                <img src="{{ MEDIA_URL }}no-image.jpg"  class="card-image-detail card-img-top"
                    alt="{{ product.name }}">
            </a>
            {% endif %}
        </div>
        <div class="col-lg-4 col-xl-5 col-sm-10 mt-3">
            <h2 class="fjalla-font text-danger"><strong>{{ product.name }} {% if product.platform != null %}
                    ({{ product.platform }}){% endif %}</strong></h2>
            <p class="unstyled no-margin">{% if product.category.name == 'video_games' %}PEGI Rating:
                {{ product.age_rating }}{% elif product.category.name == 'board_games' %}For Ages:
                {{ product.age_rating }}{% elif product.category.name == 'music' %} Advisory:
                {{ product.age_rating }}{% else %}Age Rating: N/A{% endif %} | <a href="#" class="text-dark"><i
                        class="fas fa-tag"></i> {{ product.category.friendly_name }}</a>
            </a>
            {% if product.category.name == 'music' %}
            <small>Genre | {{ product.genre }}</small>
            <br>
            {% endif %}
            <hr>
            <h4>Price: <strong class="fjalla-font text-danger">£{{ product.price }}</strong></h4>
            <hr>
            <h3><strong>Description:</strong></h3>
            <p>{{ product.description }}</p>
            <div class="mt-4 mb-3">
                <form action="{% url 'add_to_basket' product.id %}" method="POST" class="form">
                    {% csrf_token %}
                    {% if product.category.name == 'clothing' and product.sizes %}
                    <h4>Select a size</h4>
                    <select name="product_size" class="shadows-font bold-font border-0" id="id_product_size">
                        <option value="XS" class="bold-font shadows-font">XS</option>
                        <option value="S" class="bold-font shadows-font">S</option>
                        <option value="M" class="bold-font shadows-font">M</option>
                        <option value="L" class="bold-font shadows-font">L</option>
                        <option value="XL" class="bold-font shadows-font">XL</option>
                    </select>
                    {% endif %}
                    {% if product.category.name == 'tech' %}
                    {% else %}
                    <h4 class="mt-3"><strong>Quantity:</strong></h4>
                    <div class="w-25 form-group my-3">
                        <div class="input-group mb-3">
                            <input type="number" name="quantity" class="qty_input form-control" value="1" min="1"
                                max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                        </div>
                    </div>
                    {% endif %}
                    <input type="submit" value="Add to Basket" class="btn btn-lg bold-font btn-danger">
                    <a href="{% url 'products' %}" class="btn btn-lg btn-dark text-white">
                        <strong>Keep Shopping</strong>
                    </a>
                    {% if user.is_superuser %}
                    <a href="{% url 'edit_product' product.id %}" class="btn btn-lg btn-success text-white">
                        <strong>Edit Product</strong>
                    </a>
                    <a href="{% url 'delete_product' product.id %}" class="btn btn-lg btn-warning text-dark">
                        <strong>Delete Product</strong>
                    </a>
                    {% endif %}
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">

                </form>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        {% if product.reviews.all %}
        <div class="row">
            <div class="col-12 col-sm-6 offset-3 mt-3 ">
                <h2 class="fjalla-font text-danger text-center">
                    <strong>User Reviews</strong>
                </h2>
                {% for review in product.reviews.all %}
                <div class="col-xl-3 col-xxl-2 col-lg-4 col-sm-6 mt-3 mb-3">
                    <div class="card border-1 h-100">
                        <div class="card-body text-center">
                            <strong>
                                <h5 class="text-danger fjalla-font">User Review:</h5>
                            </strong>
                            <p class="card-text">{{ review.user_review }}</p>
                            <p><small><i class="fas fa-star"></i> Rating:</small> {{ review.rate }} /
                                5
                            </p>
                        </div>
                        <div class="card-footer bg-white">
                            <div class="row">
                                <div class="col">
                                    <p>Reviewed by: <small>{{ review.user }}</small></p>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            {% endfor %}
            {% endif %}
            {% if user.is_authenticated %}
            <div class="row">
                <div class="col-12 col-sm-6 offset-3 ">
                    <h1 class="fjalla-font text-danger text-center">
                        <strong>Leave a Review</strong>
                    </h1>
                    <form method="POST" action="{% url 'product_review' product.id %}">
                        {% csrf_token %}
                        {{ form.user_review | as_crispy_field }}
                        {{ form.rate | as_crispy_field }}
                        <button class="btn-danger btn-lg btn white-text" type="submit">
                            Submit Review
                        </button>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>

    {% endblock %}

    {% block postloadjs %}
    {{ block.super }}
    {% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row mt-2">
        <div class="col text-center">
            <h2 class="fjalla-font text-danger">
                Products
            </h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 offset-md-1 col-12 justify-content-md-start justify-content-center d-flex">
            <div class="sort-select-wrapper">
                <p class="text-muted mt-3 text-center text-md-left">
                    {% if search_term or current_categories or current_sorting != 'None_None' %}
                    <span class="small"><a href="{% url 'products' %}">Products Home</a> | </span>
                    {% endif %}
                    {{ products|length }} Products{% if search_term %} found for
                    <strong>"{{ search_term }}"</strong>{% endif %}
                </p>
                <select name="sort" id="sort-selector"
                    class="custom-select custom-select-sm rounded-0 border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                    <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...
                    </option>
                    <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price
                        (low to high)</option>
                    <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price
                        (high to low)</option>
                    <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name
                        (A-Z)</option>
                    <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name
                        (Z-A)</option>
                    <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>
                        Category (A-Z)</option>
                    <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>
                        Category (Z-A)</option>
                </select>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-10 offset-1">
            <div class="row ">
                {% for product in products %}
                <div class="col-xl-3 col-xxl-2 col-lg-4 col-sm-6 mt-3 mb-3">
                    <div class="card border-1 h-100">
                        {% if product.image %}
                        <a href="{% url 'product_detail' product.id %}" class="mx-auto">
                            <img src="{{ product.image.url }}" class="card-image card-img-top img-fluid"
                                alt="{{ product.name }}">
                        </a>
                        {% else %}
                        <a href="{% url 'product_detail' product.id %}" class="mx-auto">
                            <img src="{{ MEDIA_URL }}no-image.jpg" class="card-image card-img-top img-fluid"
                                alt="{{ product.name }}">
                        </a>
                        {% endif %}

                        <div class="card-body text-center">
                            <a href="{% url 'product_detail' product.id %}" class="text-black">
                                <p class="card-text"><strong>{{ product.name }}{% if product.platform != null %}
                                        ({{ product.platform }}){% endif %}</strong></p>
                            </a>
                            <small>{% if product.category.name == 'video_games' %}PEGI Rating:
                                {{ product.age_rating }}{% elif product.category.name == 'board_games' %}For
                                Ages:
                                {{ product.age_rating }}{% else %}Age Rating: N/A{% endif %}</small>
                        </div>
                        <div class="card-footer bg-white">
                            <div class="row">
                                <div class="col">
                                    <small><i class="fas fa-wallet"></i></small>
                                    <p> £{{ product.price }}</p>
                                    <a href="" class="text-black unstyled">
                                        <small><i class="fas fa-tag"></i></small>
                                        <p>
                                            {{ product.category.friendly_name }}</p>
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#sort-selector').change(function () {
        var selector = $(this);
        var currentUrl = new URL(window.location);

        var selectedVal = selector.val();
        if (selectedVal != "reset") {
            var sort = selectedVal.split("_")[0];
            var direction = selectedVal.split("_")[1];

            currentUrl.searchParams.set("sort", sort);
            currentUrl.searchParams.set("direction", direction);

            window.location.replace(currentUrl);
        } else {
            currentUrl.searchParams.delete("sort");
            currentUrl.searchParams.delete("direction");

            window.location.replace(currentUrl);
        }
    })
</script>
{% endblock %}